<?php
/**
 * @file
 * hot_alerts.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function hot_alerts_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_alert_type'
  $field_bases['field_alert_type'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_alert_type',
    'foreign keys' => array(),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'locked' => 0,
    'module' => 'list',
    'settings' => array(
      'allowed_values' => array(
        'alert-success' => 'Success',
        'alert-info' => 'Info',
        'alert-warning' => 'Warning',
        'alert-danger' => 'Danger',
      ),
      'allowed_values_function' => '',
    ),
    'translatable' => 0,
    'type' => 'list_text',
  );

  // Exported field_base: 'field_hs_alerts_description'
  $field_bases['field_hs_alerts_description'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_hs_alerts_description',
    'foreign keys' => array(
      'format' => array(
        'columns' => array(
          'format' => 'format',
        ),
        'table' => 'filter_format',
      ),
    ),
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'text_long',
  );

  return $field_bases;
}
